### ISSUE TITLE
Updating YAML-template-based CloudFormation stacks fails due to internal JSON parsing attempt

### ISSUE THREAD

**Issue by Igrom** [Rhosys/aws-architect.js#52]
When updating a CloudFormation stack written in YAML, calling 
```
awsArchitect.deployTemplate(stackTemplate, stackConfiguration, parameters)
```
when using aws-architect v6.6.15 fails with the following error: 
```
SyntaxError: Unexpected token A in JSON at position 0
    at JSON.parse (<anonymous>)
    at CloudFormationDeployer.deployTemplate (/$home/$project/node_modules/aws-architect/lib/CloudFormationDeployer.js:196:24)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async /$home/$project/bin/deploy.js:53:9
```

The following excerpt from CloudFormationDeployer.js seems to be the culprit:
```
    if (stackExists) {
      const currentStackTemplate = await this.cloudFormationClient.getTemplate({ StackName: options.stackName, TemplateStage: 'Original' }).promise();
      const currentStackData = await this.cloudFormationClient.describeStacks({ StackName: options.stackName }).promise().then(data => data.Stacks[0]);
      if (isEqual(JSON.parse(currentStackTemplate.TemplateBody.trim()), JSON.parse(templateString.trim()))
        && Object.keys(parameters).every(key => currentStackData.Parameters.find(p => p.ParameterKey === key && p.ParameterValue === parameters[key]))) {
        console.log('Skipping deployment of stack because template matches existing CF stack template');
        return Object.assign({ title: 'Change set skipped, no changes detected.', code: 'SKIPPED' }, currentStackData);
      }
    }
```
The return value of `this.cloudFormationClient.getTemplate(...)` appears to include the original YAML version of the template. Calling `JSON.parse(...)` on it results in a SyntaxError.

Workaround

Version 6.5.649 works.

**Comment by wparad** [comment]
Should we just exclude the optimization for yaml based templates, or is there an alternative that would allow us to compare the current version to the what is saved?

**Comment by Igrom** [comment]
My assumption being that the YAML template is not modified by AWS, I suspect that first converting both the local and the remote template version from YAML to JSON and only then comparing them could yield the intended result.

Admittedly, I haven't read much into what the optimization at that point in the code is, but I think my way is sound as a highly localized fix.

**Comment by wparad** [comment]
The prevents deploying a change set and short circuiting if the CF template is semantically the same as what is already deployed. 

* The short term fix is to wrap the code block in a try/catch. (feel free to put a PR, or let me know here, and I can do it).
* The long term fix would be to actually understand what happens with a yaml template, and whether or not there is something that can be compared at all, and if so how, is a blanket string compare sufficient or do we need to convert to JSON. if we convert to JSON, does the check even work, or is there something about the conversion that makes it non-deterministic because of what is saved in AWS.

**Comment by wparad** [comment]
Updated this to handle the yaml, it will do a straight comparison so if what is returned from CFN doesn't match the optimization won't work. I recommend trying it out and potentially validating it with a yaml template and see what the api returns. Otherwise you can find the fix in the latest version of the library.
